services:
  regular:
    image: regular
    build:
      context: .
      dockerfile: regular.Dockerfile
    tty: true
    volumes:
      - ./docs:/app/docs
      - ./reference:/app/reference
      - ./tests:/app/tests
      - ./text_dedup:/app/text_dedup

  spark:
    image: spark
    build:
      context: .
      dockerfile: spark.Dockerfile
    tty: true
    volumes:
      - ./tests:/app/tests
      - ./text_dedup:/app/text_dedup
