services:
  local:
    image: local
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./docs:/app/docs
      - ./tests:/app/tests
      - ./text_dedup:/app/text_dedup
      - ./data:/app/data
